### PR TITLE
Add vips

### PR DESCRIPTION
**Pull request by glenrobson**

### CODE REVIEW

**Review by ruven — COMMENTED** [review]
The "Q" parameter controls the JPEG quality level and doesn't affect LZW compression. If you want to optimize LZW (and also Deflate) compression for color images, you can replace the Q parameter with `--predictor horizontal`, which can usually shave a few extra % off the file size

**Comment by glenrobson** [comment]
Add loss less and use jpeg for lossy.

**Comment by ruven** [comment]
Well, technically no compression is indeed lossless ;-)

But I suggest we also use something like Deflate to allow us to have a full equivalent comparison of file size and decoding speed with respect to lossless HTJ2K:

`--predictor deflate`

**Comment by glenrobson** [comment]
It looks like VIPS only supports the following:

```
predictor    - Compression prediction, input VipsForeignTiffPredictor
			default: horizontal
			allowed: none, horizontal, float
```

**Comment by glenrobson** [comment]
but it does support:

```
--compression deflate 
```

**Comment by ruven** [comment]
Sorry, I meant to write:

`--compression deflate`

**Pull request merged**
